development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: task_viewer_production

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: task_viewer_production
